version: '3.9'

services:
  web:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    image: ${ECR_REGISTRY}/pycheck:v1.0
    command: ["python", "run.py"]
    ports:
      - "80:80"
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - SECRET_KEY
      - SESSION_TIMEOUT
      - FLASK_HOST
      - FLASK_PORT
      - DATABASE_HOST
      - DATABASE_PORT
      - DATABASE_NAME

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
